# Generated by Django 2.0.2 on 2018-02-04 20:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A varos neve', max_length=40)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Heating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(help_text='Futes tipusa', max_length=40)),
            ],
            options={
                'ordering': ['kind'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID', primary_key=True, serialize=False)),
                ('size', models.PositiveSmallIntegerField(help_text='Méret')),
                ('rooms', models.PositiveSmallIntegerField(help_text='Szobak szama')),
                ('half_rooms', models.PositiveSmallIntegerField(help_text='Felszobak szama')),
                ('number_of_floors', models.PositiveSmallIntegerField(help_text='Szintek szama')),
                ('on_floor', models.PositiveSmallIntegerField(help_text='Hanyadik emelet')),
                ('added_at', models.DateTimeField(auto_now_add=True, help_text='Hozzaadas datuma')),
                ('extras', models.TextField(help_text='Tartozek', max_length=120)),
                ('description', models.TextField(help_text='Leiras')),
                ('price', models.BigIntegerField(help_text='Ar')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.City')),
                ('heating', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Heating')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_state', models.CharField(help_text='Ingatlan allapota (uj/ujszeru/felujitott)', max_length=40)),
            ],
            options={
                'ordering': ['property_state'],
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(help_text='Az ingatlan tipusa(csaladi haz, lakas, stb.)', max_length=40)),
            ],
            options={
                'ordering': ['property_type'],
            },
        ),
        migrations.AddField(
            model_name='property',
            name='property_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.PropertyState'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.PropertyType'),
        ),
    ]
